# kube-prometheus-stack-values-tenant-cluster-venus.yaml
#
# based on https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
#
prometheus:
  enabled: true
  service:
    type: NodePort
  prometheusSpec:
    remoteWrite:
      - url: http://<the-ip-address-of-jupiter-control-plane>:30123/api/v1/push
        headers:
          X-Scope-OrgID: cluster-venus
    externalLabels:
      __tenant_id__ : cluster-venus
grafana:
  enabled: false
alertmanager:
  enabled: false