apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: workload-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-role
subjects:
- kind: ServiceAccount
  name: workload-sa
  namespace: default
