spec:
  ports:
  - name: http
    nodePort: 30090
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: https
    nodePort: 30443
    port: 9443
    protocol: TCP
    targetPort: 9443
  type: NodePort